### ISSUE TITLE
CustomerReview method names on README.md are different from code.

### ISSUE THREAD

**Issue by shirakiya** [chakki-works/chazutsu#2]
CustomerReview class has class methods `products5`, `additional9`, `more3`.

But Datasets README.md shows CustomerReview has `5products`, `9additional`, `3more`. https://github.com/chakki-works/chazutsu/blob/master/chazutsu/datasets/README.md#customer-review-datasets

I think it is better to match documents with code. How about?

**Comment by icoxfog417** [comment]
Thank you for your pointing out the mistakes! I fixed it.
